# Generated by Django 3.2.9 on 2021-12-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishphrases',
            name='definition',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
